type TJobData = {
  status: string;
  request_id: string;
  parameters: any;
  data: {
    employer_name: string;
    employer_logo: string;
    employer_website: string;
    employer_company_type: string;
    job_publisher: string;
    job_id: string;
    job_employment_type: string;
    job_title: string;
    job_apply_link: string;
    job_apply_is_direct: boolean;
    job_apply_quality_score: number;
    job_description: string;
    job_is_remote: boolean;
    job_posted_at_timestamp: number;
    job_posted_at_datetime_utc: string;
    job_city: string;
    job_state: string;
    job_country: string;
    job_latitude: number;
    job_longitude: number;
    job_benefits: string;
    job_google_link: string;
    job_offer_expiration_datetime_utc: string;
    job_offer_expiration_timestamp: number;
    job_required_experience: {};
    job_required_skills: {};
    job_required_education: {};
    job_experience_in_place_of_education: boolean;
    job_min_salary: number;
    job_max_salary: number;
    job_salary_currency: number;
    job_salary_period: number;
    job_highlights: {};
    job_job_title: string;
    job_posting_language: string;
    job_onet_soc: string;
    job_onet_job_zone: string;
    job_naics_code: string;
    job_naics_name: string;
  }[];
};

type TDummyData = {
  job_id: string;
  employer_logo: string;
  job_title: string;
  employer_name: string;
  job_country: string;
  job_employment_type: string;
  job_highlights: {
    Qualifications: string[];
    Responsibilities: string[];
  };
  job_description: string;
  job_google_link: string;
};
